Reject sourcemap before sending it to uglify (#63)
* Reject sourcemap before sending it to uglify

At some point today, our builds started failing with a sourcemap error
from this lib. Running the tests here makes it replicable:

```
  ● allow to disable source maps

    DefaultsError: `sourcemap` is not a supported option

      at DefaultsError.get (eval at <anonymous> (node_modules/uglify-js/tools/node.js:20:1), <anonymous>:71:23)
```

This fixes the error by rejecting the option uglify is now rejecting
before the whole thing crashes.

* Use delete to mutate options object instead of a new copy

* Upgrade serialize-javascript